Add helm chart and skaffold manifest
rayyanqcri/rayyan-store-proxy pull request #11
Opened 2020-09-22 13:53 UTC by fabubaker

- Add new helm chart for rayyan-store.
- Add skaffold.yaml.
- Replace old pipeline with new multi-stage pipeline.

2020-09-22 14:02 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +      PROXY_PORT: 3000
Need to add `NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY` to `env`.

2020-09-22 14:20 UTC, hammady requested changes

2020-09-22 14:20 UTC, hammady commented on azure-pipelines.yml
> -- task: Docker@1
Interesting, we had tests for RSP. Let's add an issue to add a [test stage](https://skaffold.dev/docs/pipeline-stages/testers/) to skaffold and use the [command tests](https://github.com/GoogleContainerTools/container-structure-test#command-tests) to invoke tests. We should address this in a separate scope.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/Chart.yaml
> +  version: 0.3.0
Please use `1.0.0` once it is merged to make use of the deployment/pod labels to attach chart version.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/templates/secrets/rayyan-store-proxy-redis.yaml
> +  REDIS_URL: {{ .Values.secrets.RAYYAN_STORE_PROXY_REDIS_URL }}
Now you can de-scope the secret name (no more monolith chart):
```suggestion
  REDIS_URL: {{ .Values.secrets.REDIS_URL }}
```

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/value-overrides/staging.yaml
> +    replicas: 1
Not needed.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
We don't need that much in staging.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +      timeoutSeconds: 5
An empty ` secrets: {} ` is necessary so that the chart can be deployed without any overrides.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/value-overrides/staging.yaml
> +      NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY: RayyanStoreProxy Staging (AKS)
Is this right or it doesn't have `_RAYYAN_STORE_PROXY`?

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/value-overrides/staging.yaml
> +      NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY: RayyanStoreProxy Staging (AKS)
Also I couldn't find this variable on live staging.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +      RAYYAN_STORE_READ_TIMEOUT: 30
I couldn't find this variable on live staging.

2020-09-22 14:20 UTC, hammady commented on helm/rayyan-store-proxy/value-overrides/prod.yaml
> +      NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY: RayyanStoreProxy Production (AKS)
This variable name can be shorter (even with the previous monolith).

2020-09-22 14:39 UTC, fabubaker commented on azure-pipelines.yml
> -- task: Docker@1
Done, see https://github.com/rayyanqcri/rayyan-store-proxy/issues/12.

2020-09-22 14:59 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
I'm going to go on a limb here and say we don't need it for prod either. I propose reducing cpu to 100m by default.

2020-09-22 15:02 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +      RAYYAN_STORE_READ_TIMEOUT: 30
`RAYYAN_STORE_READ_TIMEOUT` is by default set to 30 seconds in the app, I'm going to remove this from the manifests.

2020-09-22 15:05 UTC, fabubaker commented on azure-pipelines.yaml
> +    ref: refs/heads/test-staging
Done.

2020-09-22 15:05 UTC, fabubaker commented on helm/rayyan-store-proxy/templates/secrets/rayyan-store-proxy-redis.yaml
> +  REDIS_URL: {{ .Values.secrets.RAYYAN_STORE_PROXY_REDIS_URL }}
Done.

2020-09-22 15:05 UTC, fabubaker commented on helm/rayyan-store-proxy/value-overrides/staging.yaml
> +    replicas: 1
Done.

2020-09-22 15:05 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +      timeoutSeconds: 5
Done.

2020-09-22 15:06 UTC, fabubaker commented on helm/rayyan-store-proxy/value-overrides/prod.yaml
> +      NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY: RayyanStoreProxy Production (AKS)
Shortened it to just `NEW_RELIC_APP_NAME`.

2020-09-22 15:07 UTC, fabubaker commented on helm/rayyan-store-proxy/value-overrides/staging.yaml
> +      NEW_RELIC_APP_NAME_RAYYAN_STORE_PROXY: RayyanStoreProxy Staging (AKS)
Not sure why it's not there now, but we should have it anyways.

2020-09-22 17:00 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
Do you have data to support this new `requests`?

2020-09-22 17:03 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
I'm basing off of NR:

![image](https://user-images.githubusercontent.com/9405286/93914035-9dfa0880-fd0e-11ea-8529-c9e33b7340b5.png)

2020-09-23 06:18 UTC, fabubaker commented on helm/rayyan-store-proxy/Chart.yaml
> +  version: 0.3.0
Done.

2020-09-23 06:30 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
You changed memory but not cpu.

2020-09-23 06:33 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
Huh, I haven't changed anything yet, waiting for your approval.

To confirm, cpu -> 100m and memory stays the same at 0.1G.

2020-09-23 08:07 UTC, hammady commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
I thought it was not `0.1G`, this force-pushing is making me lose confidence in changes! OK if these values are enough.

2020-09-23 08:26 UTC, fabubaker commented on helm/rayyan-store-proxy/values.yaml
> +        cpu: 300m
Done.

2020-09-23 11:08 UTC, hammady approved these changes

2020-09-23 11:09 UTC, merged